# external management and rpc ports
apiVersion: v1
kind: Service
metadata:
  name: ognb-ex-0
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 32000
      name: rpc
    - port: 8002
      nodePort: 30002
      name: websocket
    - port: 8003
      nodePort: 30003
      name: profiling
  selector:
    statefulset.kubernetes.io/pod-name: ognb-0
