apiVersion: v1
kind: Service
metadata: {name: ognb-ex-0}
spec:
  ports:
  - {name: rpc, nodePort: 32000, port: 8000}
  - {name: websocket, nodePort: 30002, port: 8002}
  - {name: profiling, nodePort: 30003, port: 8003}
  selector: {statefulset.kubernetes.io/pod-name: ognb-0}
  type: NodePort
