apiVersion: v1
kind: Service
metadata: {name: ognb-ex-3}
spec:
  ports:
  - {name: rpc, nodePort: 32030, port: 8000}
  - {name: websocket, nodePort: 30032, port: 8002}
  - {name: profiling, nodePort: 30033, port: 8003}
  selector: {statefulset.kubernetes.io/pod-name: ognb-3}
  type: NodePort
