apiVersion: v1
kind: Service
metadata: {name: ognb-ex-6}
spec:
  ports:
  - {name: rpc, nodePort: 32060, port: 8000}
  - {name: websocket, nodePort: 30062, port: 8002}
  - {name: profiling, nodePort: 30063, port: 8003}
  selector: {statefulset.kubernetes.io/pod-name: ognb-6}
  type: NodePort
