apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-601
  labels:
    target: og
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /alidata1/nfs/v1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - izuf6a8si7x4swoav7odv8z

