package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (h *Address) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	err = dc.ReadExactBytes((h.Bytes)[:])
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (h *Address) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	err = en.WriteBytes((h.Bytes)[:])
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (h *Address) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, h.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	o = msgp.AppendBytes(o, (h.Bytes)[:])
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (h *Address) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (h.Bytes)[:])
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (h *Address) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize + (AddressLength * (msgp.ByteSize))
	return
}
