package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/annchain/OG/common/math"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BloomFilter) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Data, err = dc.ReadBytes(z.Data)
	if err != nil {
		return
	}
	z.Count, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *BloomFilter) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Count)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *BloomFilter) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendBytes(o, z.Data)
	o = msgp.AppendUint32(o, z.Count)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BloomFilter) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
	if err != nil {
		return
	}
	z.Count, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BloomFilter) Msgsize() (s int) {
	s = 1 + msgp.BytesPrefixSize + len(z.Data) + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *HashOrNumber) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	err = z.Hash.DecodeMsg(dc)
	if err != nil {
		return
	}
	z.Number, err = dc.ReadUint64()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *HashOrNumber) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = z.Hash.EncodeMsg(en)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Number)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *HashOrNumber) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o, err = z.Hash.MarshalMsg(o)
	if err != nil {
		return
	}
	o = msgp.AppendUint64(o, z.Number)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *HashOrNumber) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	bts, err = z.Hash.UnmarshalMsg(bts)
	if err != nil {
		return
	}
	z.Number, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *HashOrNumber) Msgsize() (s int) {
	s = 1 + z.Hash.Msgsize() + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageBodiesRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.SeqHashes) >= int(zb0002) {
		z.SeqHashes = (z.SeqHashes)[:zb0002]
	} else {
		z.SeqHashes = make([]Hash, zb0002)
	}
	for za0001 := range z.SeqHashes {
		err = z.SeqHashes[za0001].DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	z.RequestId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageBodiesRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.SeqHashes)))
	if err != nil {
		return
	}
	for za0001 := range z.SeqHashes {
		err = z.SeqHashes[za0001].EncodeMsg(en)
		if err != nil {
			return
		}
	}
	err = en.WriteUint32(z.RequestId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageBodiesRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendArrayHeader(o, uint32(len(z.SeqHashes)))
	for za0001 := range z.SeqHashes {
		o, err = z.SeqHashes[za0001].MarshalMsg(o)
		if err != nil {
			return
		}
	}
	o = msgp.AppendUint32(o, z.RequestId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageBodiesRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.SeqHashes) >= int(zb0002) {
		z.SeqHashes = (z.SeqHashes)[:zb0002]
	} else {
		z.SeqHashes = make([]Hash, zb0002)
	}
	for za0001 := range z.SeqHashes {
		bts, err = z.SeqHashes[za0001].UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	z.RequestId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageBodiesRequest) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.SeqHashes {
		s += z.SeqHashes[za0001].Msgsize()
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageBodiesResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.Bodies) >= int(zb0002) {
		z.Bodies = (z.Bodies)[:zb0002]
	} else {
		z.Bodies = make([]RawData, zb0002)
	}
	for za0001 := range z.Bodies {
		{
			var zb0003 []byte
			zb0003, err = dc.ReadBytes([]byte(z.Bodies[za0001]))
			if err != nil {
				return
			}
			z.Bodies[za0001] = RawData(zb0003)
		}
	}
	z.RequestedId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageBodiesResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Bodies)))
	if err != nil {
		return
	}
	for za0001 := range z.Bodies {
		err = en.WriteBytes([]byte(z.Bodies[za0001]))
		if err != nil {
			return
		}
	}
	err = en.WriteUint32(z.RequestedId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageBodiesResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Bodies)))
	for za0001 := range z.Bodies {
		o = msgp.AppendBytes(o, []byte(z.Bodies[za0001]))
	}
	o = msgp.AppendUint32(o, z.RequestedId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageBodiesResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.Bodies) >= int(zb0002) {
		z.Bodies = (z.Bodies)[:zb0002]
	} else {
		z.Bodies = make([]RawData, zb0002)
	}
	for za0001 := range z.Bodies {
		{
			var zb0003 []byte
			zb0003, bts, err = msgp.ReadBytesBytes(bts, []byte(z.Bodies[za0001]))
			if err != nil {
				return
			}
			z.Bodies[za0001] = RawData(zb0003)
		}
	}
	z.RequestedId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageBodiesResponse) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.Bodies {
		s += msgp.BytesPrefixSize + len([]byte(z.Bodies[za0001]))
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageHeaderRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 5 {
		err = msgp.ArrayError{Wanted: 5, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0002 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0002}
		return
	}
	err = z.Origin.Hash.DecodeMsg(dc)
	if err != nil {
		return
	}
	z.Origin.Number, err = dc.ReadUint64()
	if err != nil {
		return
	}
	z.Amount, err = dc.ReadUint64()
	if err != nil {
		return
	}
	z.Skip, err = dc.ReadUint64()
	if err != nil {
		return
	}
	z.Reverse, err = dc.ReadBool()
	if err != nil {
		return
	}
	z.RequestId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageHeaderRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 5
	// array header, size 2
	err = en.Append(0x95, 0x92)
	if err != nil {
		return
	}
	err = z.Origin.Hash.EncodeMsg(en)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Origin.Number)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Amount)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Skip)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Reverse)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.RequestId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageHeaderRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 5
	// array header, size 2
	o = append(o, 0x95, 0x92)
	o, err = z.Origin.Hash.MarshalMsg(o)
	if err != nil {
		return
	}
	o = msgp.AppendUint64(o, z.Origin.Number)
	o = msgp.AppendUint64(o, z.Amount)
	o = msgp.AppendUint64(o, z.Skip)
	o = msgp.AppendBool(o, z.Reverse)
	o = msgp.AppendUint32(o, z.RequestId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageHeaderRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 5 {
		err = msgp.ArrayError{Wanted: 5, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0002 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0002}
		return
	}
	bts, err = z.Origin.Hash.UnmarshalMsg(bts)
	if err != nil {
		return
	}
	z.Origin.Number, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	z.Amount, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	z.Skip, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	z.Reverse, bts, err = msgp.ReadBoolBytes(bts)
	if err != nil {
		return
	}
	z.RequestId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageHeaderRequest) Msgsize() (s int) {
	s = 1 + 1 + z.Origin.Hash.Msgsize() + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint64Size + msgp.BoolSize + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageHeaderResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.RawSequencers) >= int(zb0002) {
		z.RawSequencers = (z.RawSequencers)[:zb0002]
	} else {
		z.RawSequencers = make([]*RawSequencer, zb0002)
	}
	for za0001 := range z.RawSequencers {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				return
			}
			z.RawSequencers[za0001] = nil
		} else {
			if z.RawSequencers[za0001] == nil {
				z.RawSequencers[za0001] = new(RawSequencer)
			}
			err = z.RawSequencers[za0001].DecodeMsg(dc)
			if err != nil {
				return
			}
		}
	}
	z.RequestedId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageHeaderResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.RawSequencers)))
	if err != nil {
		return
	}
	for za0001 := range z.RawSequencers {
		if z.RawSequencers[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.RawSequencers[za0001].EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	err = en.WriteUint32(z.RequestedId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageHeaderResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendArrayHeader(o, uint32(len(z.RawSequencers)))
	for za0001 := range z.RawSequencers {
		if z.RawSequencers[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.RawSequencers[za0001].MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	o = msgp.AppendUint32(o, z.RequestedId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageHeaderResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.RawSequencers) >= int(zb0002) {
		z.RawSequencers = (z.RawSequencers)[:zb0002]
	} else {
		z.RawSequencers = make([]*RawSequencer, zb0002)
	}
	for za0001 := range z.RawSequencers {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.RawSequencers[za0001] = nil
		} else {
			if z.RawSequencers[za0001] == nil {
				z.RawSequencers[za0001] = new(RawSequencer)
			}
			bts, err = z.RawSequencers[za0001].UnmarshalMsg(bts)
			if err != nil {
				return
			}
		}
	}
	z.RequestedId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageHeaderResponse) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.RawSequencers {
		if z.RawSequencers[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.RawSequencers[za0001].Msgsize()
		}
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageNewSequencer) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.RawSequencer = nil
	} else {
		if z.RawSequencer == nil {
			z.RawSequencer = new(RawSequencer)
		}
		err = z.RawSequencer.DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.Filter = nil
	} else {
		if z.Filter == nil {
			z.Filter = new(BloomFilter)
		}
		var zb0002 uint32
		zb0002, err = dc.ReadArrayHeader()
		if err != nil {
			return
		}
		if zb0002 != 2 {
			err = msgp.ArrayError{Wanted: 2, Got: zb0002}
			return
		}
		z.Filter.Data, err = dc.ReadBytes(z.Filter.Data)
		if err != nil {
			return
		}
		z.Filter.Count, err = dc.ReadUint32()
		if err != nil {
			return
		}
	}
	z.Hop, err = dc.ReadUint8()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageNewSequencer) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	if z.RawSequencer == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.RawSequencer.EncodeMsg(en)
		if err != nil {
			return
		}
	}
	if z.Filter == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// array header, size 2
		err = en.Append(0x92)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.Filter.Data)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.Filter.Count)
		if err != nil {
			return
		}
	}
	err = en.WriteUint8(z.Hop)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageNewSequencer) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	if z.RawSequencer == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.RawSequencer.MarshalMsg(o)
		if err != nil {
			return
		}
	}
	if z.Filter == nil {
		o = msgp.AppendNil(o)
	} else {
		// array header, size 2
		o = append(o, 0x92)
		o = msgp.AppendBytes(o, z.Filter.Data)
		o = msgp.AppendUint32(o, z.Filter.Count)
	}
	o = msgp.AppendUint8(o, z.Hop)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageNewSequencer) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.RawSequencer = nil
	} else {
		if z.RawSequencer == nil {
			z.RawSequencer = new(RawSequencer)
		}
		bts, err = z.RawSequencer.UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.Filter = nil
	} else {
		if z.Filter == nil {
			z.Filter = new(BloomFilter)
		}
		var zb0002 uint32
		zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			return
		}
		if zb0002 != 2 {
			err = msgp.ArrayError{Wanted: 2, Got: zb0002}
			return
		}
		z.Filter.Data, bts, err = msgp.ReadBytesBytes(bts, z.Filter.Data)
		if err != nil {
			return
		}
		z.Filter.Count, bts, err = msgp.ReadUint32Bytes(bts)
		if err != nil {
			return
		}
	}
	z.Hop, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageNewSequencer) Msgsize() (s int) {
	s = 1
	if z.RawSequencer == nil {
		s += msgp.NilSize
	} else {
		s += z.RawSequencer.Msgsize()
	}
	if z.Filter == nil {
		s += msgp.NilSize
	} else {
		s += 1 + msgp.BytesPrefixSize + len(z.Filter.Data) + msgp.Uint32Size
	}
	s += msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageNewTx) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.RawTx = nil
	} else {
		if z.RawTx == nil {
			z.RawTx = new(RawTx)
		}
		err = z.RawTx.DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageNewTx) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	if z.RawTx == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.RawTx.EncodeMsg(en)
		if err != nil {
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageNewTx) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	if z.RawTx == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.RawTx.MarshalMsg(o)
		if err != nil {
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageNewTx) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.RawTx = nil
	} else {
		if z.RawTx == nil {
			z.RawTx = new(RawTx)
		}
		bts, err = z.RawTx.UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageNewTx) Msgsize() (s int) {
	s = 1
	if z.RawTx == nil {
		s += msgp.NilSize
	} else {
		s += z.RawTx.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageNewTxs) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.RawTxs) >= int(zb0002) {
		z.RawTxs = (z.RawTxs)[:zb0002]
	} else {
		z.RawTxs = make([]*RawTx, zb0002)
	}
	for za0001 := range z.RawTxs {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				return
			}
			z.RawTxs[za0001] = nil
		} else {
			if z.RawTxs[za0001] == nil {
				z.RawTxs[za0001] = new(RawTx)
			}
			err = z.RawTxs[za0001].DecodeMsg(dc)
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageNewTxs) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.RawTxs)))
	if err != nil {
		return
	}
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.RawTxs[za0001].EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageNewTxs) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	o = msgp.AppendArrayHeader(o, uint32(len(z.RawTxs)))
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.RawTxs[za0001].MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageNewTxs) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.RawTxs) >= int(zb0002) {
		z.RawTxs = (z.RawTxs)[:zb0002]
	} else {
		z.RawTxs = make([]*RawTx, zb0002)
	}
	for za0001 := range z.RawTxs {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.RawTxs[za0001] = nil
		} else {
			if z.RawTxs[za0001] == nil {
				z.RawTxs[za0001] = new(RawTx)
			}
			bts, err = z.RawTxs[za0001].UnmarshalMsg(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageNewTxs) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.RawTxs[za0001].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessagePing) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "Data":
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessagePing) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Data"
	err = en.Append(0x81, 0xa4, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessagePing) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Data"
	o = append(o, 0x81, 0xa4, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Data)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessagePing) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "Data":
			z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessagePing) Msgsize() (s int) {
	s = 1 + 5 + msgp.BytesPrefixSize + len(z.Data)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessagePong) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "Data":
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessagePong) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Data"
	err = en.Append(0x81, 0xa4, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessagePong) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Data"
	o = append(o, 0x81, 0xa4, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Data)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessagePong) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "Data":
			z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessagePong) Msgsize() (s int) {
	s = 1 + 5 + msgp.BytesPrefixSize + len(z.Data)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageSequencerHeader) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.Hash = nil
	} else {
		if z.Hash == nil {
			z.Hash = new(Hash)
		}
		err = z.Hash.DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	z.Number, err = dc.ReadUint64()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageSequencerHeader) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	if z.Hash == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Hash.EncodeMsg(en)
		if err != nil {
			return
		}
	}
	err = en.WriteUint64(z.Number)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageSequencerHeader) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	if z.Hash == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Hash.MarshalMsg(o)
		if err != nil {
			return
		}
	}
	o = msgp.AppendUint64(o, z.Number)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageSequencerHeader) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.Hash = nil
	} else {
		if z.Hash == nil {
			z.Hash = new(Hash)
		}
		bts, err = z.Hash.UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	z.Number, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageSequencerHeader) Msgsize() (s int) {
	s = 1
	if z.Hash == nil {
		s += msgp.NilSize
	} else {
		s += z.Hash.Msgsize()
	}
	s += msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageSyncRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.Hashes) >= int(zb0002) {
		z.Hashes = (z.Hashes)[:zb0002]
	} else {
		z.Hashes = make([]Hash, zb0002)
	}
	for za0001 := range z.Hashes {
		err = z.Hashes[za0001].DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.Filter = nil
	} else {
		if z.Filter == nil {
			z.Filter = new(BloomFilter)
		}
		var zb0003 uint32
		zb0003, err = dc.ReadArrayHeader()
		if err != nil {
			return
		}
		if zb0003 != 2 {
			err = msgp.ArrayError{Wanted: 2, Got: zb0003}
			return
		}
		z.Filter.Data, err = dc.ReadBytes(z.Filter.Data)
		if err != nil {
			return
		}
		z.Filter.Count, err = dc.ReadUint32()
		if err != nil {
			return
		}
	}
	z.RequestId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageSyncRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Hashes)))
	if err != nil {
		return
	}
	for za0001 := range z.Hashes {
		err = z.Hashes[za0001].EncodeMsg(en)
		if err != nil {
			return
		}
	}
	if z.Filter == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// array header, size 2
		err = en.Append(0x92)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.Filter.Data)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.Filter.Count)
		if err != nil {
			return
		}
	}
	err = en.WriteUint32(z.RequestId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageSyncRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Hashes)))
	for za0001 := range z.Hashes {
		o, err = z.Hashes[za0001].MarshalMsg(o)
		if err != nil {
			return
		}
	}
	if z.Filter == nil {
		o = msgp.AppendNil(o)
	} else {
		// array header, size 2
		o = append(o, 0x92)
		o = msgp.AppendBytes(o, z.Filter.Data)
		o = msgp.AppendUint32(o, z.Filter.Count)
	}
	o = msgp.AppendUint32(o, z.RequestId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageSyncRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.Hashes) >= int(zb0002) {
		z.Hashes = (z.Hashes)[:zb0002]
	} else {
		z.Hashes = make([]Hash, zb0002)
	}
	for za0001 := range z.Hashes {
		bts, err = z.Hashes[za0001].UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.Filter = nil
	} else {
		if z.Filter == nil {
			z.Filter = new(BloomFilter)
		}
		var zb0003 uint32
		zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			return
		}
		if zb0003 != 2 {
			err = msgp.ArrayError{Wanted: 2, Got: zb0003}
			return
		}
		z.Filter.Data, bts, err = msgp.ReadBytesBytes(bts, z.Filter.Data)
		if err != nil {
			return
		}
		z.Filter.Count, bts, err = msgp.ReadUint32Bytes(bts)
		if err != nil {
			return
		}
	}
	z.RequestId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageSyncRequest) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.Hashes {
		s += z.Hashes[za0001].Msgsize()
	}
	if z.Filter == nil {
		s += msgp.NilSize
	} else {
		s += 1 + msgp.BytesPrefixSize + len(z.Filter.Data) + msgp.Uint32Size
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageSyncResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.RawTxs) >= int(zb0002) {
		z.RawTxs = (z.RawTxs)[:zb0002]
	} else {
		z.RawTxs = make([]*RawTx, zb0002)
	}
	for za0001 := range z.RawTxs {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				return
			}
			z.RawTxs[za0001] = nil
		} else {
			if z.RawTxs[za0001] == nil {
				z.RawTxs[za0001] = new(RawTx)
			}
			err = z.RawTxs[za0001].DecodeMsg(dc)
			if err != nil {
				return
			}
		}
	}
	var zb0003 uint32
	zb0003, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.RawSequencers) >= int(zb0003) {
		z.RawSequencers = (z.RawSequencers)[:zb0003]
	} else {
		z.RawSequencers = make([]*RawSequencer, zb0003)
	}
	for za0002 := range z.RawSequencers {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				return
			}
			z.RawSequencers[za0002] = nil
		} else {
			if z.RawSequencers[za0002] == nil {
				z.RawSequencers[za0002] = new(RawSequencer)
			}
			err = z.RawSequencers[za0002].DecodeMsg(dc)
			if err != nil {
				return
			}
		}
	}
	z.RequestedId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageSyncResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.RawTxs)))
	if err != nil {
		return
	}
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.RawTxs[za0001].EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	err = en.WriteArrayHeader(uint32(len(z.RawSequencers)))
	if err != nil {
		return
	}
	for za0002 := range z.RawSequencers {
		if z.RawSequencers[za0002] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.RawSequencers[za0002].EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	err = en.WriteUint32(z.RequestedId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageSyncResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendArrayHeader(o, uint32(len(z.RawTxs)))
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.RawTxs[za0001].MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.RawSequencers)))
	for za0002 := range z.RawSequencers {
		if z.RawSequencers[za0002] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.RawSequencers[za0002].MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	o = msgp.AppendUint32(o, z.RequestedId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageSyncResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.RawTxs) >= int(zb0002) {
		z.RawTxs = (z.RawTxs)[:zb0002]
	} else {
		z.RawTxs = make([]*RawTx, zb0002)
	}
	for za0001 := range z.RawTxs {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.RawTxs[za0001] = nil
		} else {
			if z.RawTxs[za0001] == nil {
				z.RawTxs[za0001] = new(RawTx)
			}
			bts, err = z.RawTxs[za0001].UnmarshalMsg(bts)
			if err != nil {
				return
			}
		}
	}
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.RawSequencers) >= int(zb0003) {
		z.RawSequencers = (z.RawSequencers)[:zb0003]
	} else {
		z.RawSequencers = make([]*RawSequencer, zb0003)
	}
	for za0002 := range z.RawSequencers {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.RawSequencers[za0002] = nil
		} else {
			if z.RawSequencers[za0002] == nil {
				z.RawSequencers[za0002] = new(RawSequencer)
			}
			bts, err = z.RawSequencers[za0002].UnmarshalMsg(bts)
			if err != nil {
				return
			}
		}
	}
	z.RequestedId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageSyncResponse) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.RawTxs[za0001].Msgsize()
		}
	}
	s += msgp.ArrayHeaderSize
	for za0002 := range z.RawSequencers {
		if z.RawSequencers[za0002] == nil {
			s += msgp.NilSize
		} else {
			s += z.RawSequencers[za0002].Msgsize()
		}
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageTxsRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.Hashes) >= int(zb0002) {
		z.Hashes = (z.Hashes)[:zb0002]
	} else {
		z.Hashes = make([]Hash, zb0002)
	}
	for za0001 := range z.Hashes {
		err = z.Hashes[za0001].DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.SeqHash = nil
	} else {
		if z.SeqHash == nil {
			z.SeqHash = new(Hash)
		}
		err = z.SeqHash.DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	z.Id, err = dc.ReadUint64()
	if err != nil {
		return
	}
	z.RequestId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageTxsRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 4
	err = en.Append(0x94)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Hashes)))
	if err != nil {
		return
	}
	for za0001 := range z.Hashes {
		err = z.Hashes[za0001].EncodeMsg(en)
		if err != nil {
			return
		}
	}
	if z.SeqHash == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.SeqHash.EncodeMsg(en)
		if err != nil {
			return
		}
	}
	err = en.WriteUint64(z.Id)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.RequestId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageTxsRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 4
	o = append(o, 0x94)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Hashes)))
	for za0001 := range z.Hashes {
		o, err = z.Hashes[za0001].MarshalMsg(o)
		if err != nil {
			return
		}
	}
	if z.SeqHash == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.SeqHash.MarshalMsg(o)
		if err != nil {
			return
		}
	}
	o = msgp.AppendUint64(o, z.Id)
	o = msgp.AppendUint32(o, z.RequestId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageTxsRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.Hashes) >= int(zb0002) {
		z.Hashes = (z.Hashes)[:zb0002]
	} else {
		z.Hashes = make([]Hash, zb0002)
	}
	for za0001 := range z.Hashes {
		bts, err = z.Hashes[za0001].UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.SeqHash = nil
	} else {
		if z.SeqHash == nil {
			z.SeqHash = new(Hash)
		}
		bts, err = z.SeqHash.UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	z.Id, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	z.RequestId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageTxsRequest) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.Hashes {
		s += z.Hashes[za0001].Msgsize()
	}
	if z.SeqHash == nil {
		s += msgp.NilSize
	} else {
		s += z.SeqHash.Msgsize()
	}
	s += msgp.Uint64Size + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageTxsResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.RawTxs) >= int(zb0002) {
		z.RawTxs = (z.RawTxs)[:zb0002]
	} else {
		z.RawTxs = make([]*RawTx, zb0002)
	}
	for za0001 := range z.RawTxs {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				return
			}
			z.RawTxs[za0001] = nil
		} else {
			if z.RawTxs[za0001] == nil {
				z.RawTxs[za0001] = new(RawTx)
			}
			err = z.RawTxs[za0001].DecodeMsg(dc)
			if err != nil {
				return
			}
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			return
		}
		z.RawSequencer = nil
	} else {
		if z.RawSequencer == nil {
			z.RawSequencer = new(RawSequencer)
		}
		err = z.RawSequencer.DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	z.RequestedId, err = dc.ReadUint32()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageTxsResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.RawTxs)))
	if err != nil {
		return
	}
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.RawTxs[za0001].EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	if z.RawSequencer == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.RawSequencer.EncodeMsg(en)
		if err != nil {
			return
		}
	}
	err = en.WriteUint32(z.RequestedId)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageTxsResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendArrayHeader(o, uint32(len(z.RawTxs)))
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.RawTxs[za0001].MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	if z.RawSequencer == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.RawSequencer.MarshalMsg(o)
		if err != nil {
			return
		}
	}
	o = msgp.AppendUint32(o, z.RequestedId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageTxsResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.RawTxs) >= int(zb0002) {
		z.RawTxs = (z.RawTxs)[:zb0002]
	} else {
		z.RawTxs = make([]*RawTx, zb0002)
	}
	for za0001 := range z.RawTxs {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.RawTxs[za0001] = nil
		} else {
			if z.RawTxs[za0001] == nil {
				z.RawTxs[za0001] = new(RawTx)
			}
			bts, err = z.RawTxs[za0001].UnmarshalMsg(bts)
			if err != nil {
				return
			}
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.RawSequencer = nil
	} else {
		if z.RawSequencer == nil {
			z.RawSequencer = new(RawSequencer)
		}
		bts, err = z.RawSequencer.UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	z.RequestedId, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageTxsResponse) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize
	for za0001 := range z.RawTxs {
		if z.RawTxs[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.RawTxs[za0001].Msgsize()
		}
	}
	if z.RawSequencer == nil {
		s += msgp.NilSize
	} else {
		s += z.RawSequencer.Msgsize()
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawData) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 []byte
		zb0001, err = dc.ReadBytes([]byte((*z)))
		if err != nil {
			return
		}
		(*z) = RawData(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z RawData) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteBytes([]byte(z))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z RawData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendBytes(o, []byte(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 []byte
		zb0001, bts, err = msgp.ReadBytesBytes(bts, []byte((*z)))
		if err != nil {
			return
		}
		(*z) = RawData(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z RawData) Msgsize() (s int) {
	s = msgp.BytesPrefixSize + len([]byte(z))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawSequencer) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "TxBase":
			err = z.TxBase.DecodeMsg(dc)
			if err != nil {
				return
			}
		case "Id":
			z.Id, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "ContractHashOrder":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.ContractHashOrder) >= int(zb0002) {
				z.ContractHashOrder = (z.ContractHashOrder)[:zb0002]
			} else {
				z.ContractHashOrder = make([]Hash, zb0002)
			}
			for za0001 := range z.ContractHashOrder {
				err = z.ContractHashOrder[za0001].DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RawSequencer) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "TxBase"
	err = en.Append(0x83, 0xa6, 0x54, 0x78, 0x42, 0x61, 0x73, 0x65)
	if err != nil {
		return
	}
	err = z.TxBase.EncodeMsg(en)
	if err != nil {
		return
	}
	// write "Id"
	err = en.Append(0xa2, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Id)
	if err != nil {
		return
	}
	// write "ContractHashOrder"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48, 0x61, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ContractHashOrder)))
	if err != nil {
		return
	}
	for za0001 := range z.ContractHashOrder {
		err = z.ContractHashOrder[za0001].EncodeMsg(en)
		if err != nil {
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RawSequencer) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "TxBase"
	o = append(o, 0x83, 0xa6, 0x54, 0x78, 0x42, 0x61, 0x73, 0x65)
	o, err = z.TxBase.MarshalMsg(o)
	if err != nil {
		return
	}
	// string "Id"
	o = append(o, 0xa2, 0x49, 0x64)
	o = msgp.AppendUint64(o, z.Id)
	// string "ContractHashOrder"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48, 0x61, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ContractHashOrder)))
	for za0001 := range z.ContractHashOrder {
		o, err = z.ContractHashOrder[za0001].MarshalMsg(o)
		if err != nil {
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawSequencer) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "TxBase":
			bts, err = z.TxBase.UnmarshalMsg(bts)
			if err != nil {
				return
			}
		case "Id":
			z.Id, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				return
			}
		case "ContractHashOrder":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				return
			}
			if cap(z.ContractHashOrder) >= int(zb0002) {
				z.ContractHashOrder = (z.ContractHashOrder)[:zb0002]
			} else {
				z.ContractHashOrder = make([]Hash, zb0002)
			}
			for za0001 := range z.ContractHashOrder {
				bts, err = z.ContractHashOrder[za0001].UnmarshalMsg(bts)
				if err != nil {
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RawSequencer) Msgsize() (s int) {
	s = 1 + 7 + z.TxBase.Msgsize() + 3 + msgp.Uint64Size + 18 + msgp.ArrayHeaderSize
	for za0001 := range z.ContractHashOrder {
		s += z.ContractHashOrder[za0001].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawTx) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "TxBase":
			err = z.TxBase.DecodeMsg(dc)
			if err != nil {
				return
			}
		case "To":
			err = z.To.DecodeMsg(dc)
			if err != nil {
				return
			}
		case "Value":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}
				z.Value = nil
			} else {
				if z.Value == nil {
					z.Value = new(math.BigInt)
				}
				err = z.Value.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RawTx) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "TxBase"
	err = en.Append(0x83, 0xa6, 0x54, 0x78, 0x42, 0x61, 0x73, 0x65)
	if err != nil {
		return
	}
	err = z.TxBase.EncodeMsg(en)
	if err != nil {
		return
	}
	// write "To"
	err = en.Append(0xa2, 0x54, 0x6f)
	if err != nil {
		return
	}
	err = z.To.EncodeMsg(en)
	if err != nil {
		return
	}
	// write "Value"
	err = en.Append(0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	if z.Value == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Value.EncodeMsg(en)
		if err != nil {
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RawTx) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "TxBase"
	o = append(o, 0x83, 0xa6, 0x54, 0x78, 0x42, 0x61, 0x73, 0x65)
	o, err = z.TxBase.MarshalMsg(o)
	if err != nil {
		return
	}
	// string "To"
	o = append(o, 0xa2, 0x54, 0x6f)
	o, err = z.To.MarshalMsg(o)
	if err != nil {
		return
	}
	// string "Value"
	o = append(o, 0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	if z.Value == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Value.MarshalMsg(o)
		if err != nil {
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawTx) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "TxBase":
			bts, err = z.TxBase.UnmarshalMsg(bts)
			if err != nil {
				return
			}
		case "To":
			bts, err = z.To.UnmarshalMsg(bts)
			if err != nil {
				return
			}
		case "Value":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Value = nil
			} else {
				if z.Value == nil {
					z.Value = new(math.BigInt)
				}
				bts, err = z.Value.UnmarshalMsg(bts)
				if err != nil {
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RawTx) Msgsize() (s int) {
	s = 1 + 7 + z.TxBase.Msgsize() + 3 + z.To.Msgsize() + 6
	if z.Value == nil {
		s += msgp.NilSize
	} else {
		s += z.Value.Msgsize()
	}
	return
}
