package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Sequencer) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.Id, err = dc.ReadUint64()
	if err != nil {
		return
	}
	err = z.TxBase.DecodeMsg(dc)
	if err != nil {
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(z.ContractHashOrder) >= int(zb0002) {
		z.ContractHashOrder = (z.ContractHashOrder)[:zb0002]
	} else {
		z.ContractHashOrder = make([]Hash, zb0002)
	}
	for za0001 := range z.ContractHashOrder {
		err = z.ContractHashOrder[za0001].DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Sequencer) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Id)
	if err != nil {
		return
	}
	err = z.TxBase.EncodeMsg(en)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ContractHashOrder)))
	if err != nil {
		return
	}
	for za0001 := range z.ContractHashOrder {
		err = z.ContractHashOrder[za0001].EncodeMsg(en)
		if err != nil {
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Sequencer) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendUint64(o, z.Id)
	o, err = z.TxBase.MarshalMsg(o)
	if err != nil {
		return
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.ContractHashOrder)))
	for za0001 := range z.ContractHashOrder {
		o, err = z.ContractHashOrder[za0001].MarshalMsg(o)
		if err != nil {
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Sequencer) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.Id, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	bts, err = z.TxBase.UnmarshalMsg(bts)
	if err != nil {
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(z.ContractHashOrder) >= int(zb0002) {
		z.ContractHashOrder = (z.ContractHashOrder)[:zb0002]
	} else {
		z.ContractHashOrder = make([]Hash, zb0002)
	}
	for za0001 := range z.ContractHashOrder {
		bts, err = z.ContractHashOrder[za0001].UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Sequencer) Msgsize() (s int) {
	s = 1 + msgp.Uint64Size + z.TxBase.Msgsize() + msgp.ArrayHeaderSize
	for za0001 := range z.ContractHashOrder {
		s += z.ContractHashOrder[za0001].Msgsize()
	}
	return
}
