package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (t *TxBase) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	{
		var zb0002 uint
		zb0002, err = dc.ReadUint()
		if err != nil {
			return
		}
		t.Type = TxBaseType(zb0002)
	}
	var zb0003 uint32
	zb0003, err = dc.ReadArrayHeader()
	if err != nil {
		return
	}
	if cap(t.ParentsHash) >= int(zb0003) {
		t.ParentsHash = (t.ParentsHash)[:zb0003]
	} else {
		t.ParentsHash = make([]Hash, zb0003)
	}
	for za0001 := range t.ParentsHash {
		err = t.ParentsHash[za0001].DecodeMsg(dc)
		if err != nil {
			return
		}
	}
	t.SequenceNonce, err = dc.ReadUint64()
	if err != nil {
		return
	}
	t.Height, err = dc.ReadUint64()
	if err != nil {
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (t *TxBase) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 4
	err = en.Append(0x94)
	if err != nil {
		return
	}
	err = en.WriteUint(uint(t.Type))
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(t.ParentsHash)))
	if err != nil {
		return
	}
	for za0001 := range t.ParentsHash {
		err = t.ParentsHash[za0001].EncodeMsg(en)
		if err != nil {
			return
		}
	}
	err = en.WriteUint64(t.SequenceNonce)
	if err != nil {
		return
	}
	err = en.WriteUint64(t.Height)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (t *TxBase) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, t.Msgsize())
	// array header, size 4
	o = append(o, 0x94)
	o = msgp.AppendUint(o, uint(t.Type))
	o = msgp.AppendArrayHeader(o, uint32(len(t.ParentsHash)))
	for za0001 := range t.ParentsHash {
		o, err = t.ParentsHash[za0001].MarshalMsg(o)
		if err != nil {
			return
		}
	}
	o = msgp.AppendUint64(o, t.SequenceNonce)
	o = msgp.AppendUint64(o, t.Height)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (t *TxBase) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	{
		var zb0002 uint
		zb0002, bts, err = msgp.ReadUintBytes(bts)
		if err != nil {
			return
		}
		t.Type = TxBaseType(zb0002)
	}
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		return
	}
	if cap(t.ParentsHash) >= int(zb0003) {
		t.ParentsHash = (t.ParentsHash)[:zb0003]
	} else {
		t.ParentsHash = make([]Hash, zb0003)
	}
	for za0001 := range t.ParentsHash {
		bts, err = t.ParentsHash[za0001].UnmarshalMsg(bts)
		if err != nil {
			return
		}
	}
	t.SequenceNonce, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	t.Height, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (t *TxBase) Msgsize() (s int) {
	s = 1 + msgp.UintSize + msgp.ArrayHeaderSize
	for za0001 := range t.ParentsHash {
		s += t.ParentsHash[za0001].Msgsize()
	}
	s += msgp.Uint64Size + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (t *TxBaseType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint
		zb0001, err = dc.ReadUint()
		if err != nil {
			return
		}
		(*t) = TxBaseType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (t TxBaseType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint(uint(t))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (t TxBaseType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, t.Msgsize())
	o = msgp.AppendUint(o, uint(t))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (t *TxBaseType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint
		zb0001, bts, err = msgp.ReadUintBytes(bts)
		if err != nil {
			return
		}
		(*t) = TxBaseType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (t TxBaseType) Msgsize() (s int) {
	s = msgp.UintSize
	return
}
