package og

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *GeneralMessageOg) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	err = z.InnerMessageType.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessageType")
		return
	}
	z.InnerMessage, err = dc.ReadBytes(z.InnerMessage)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessage")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GeneralMessageOg) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = z.InnerMessageType.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessageType")
		return
	}
	err = en.WriteBytes(z.InnerMessage)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessage")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GeneralMessageOg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o, err = z.InnerMessageType.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessageType")
		return
	}
	o = msgp.AppendBytes(o, z.InnerMessage)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GeneralMessageOg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	bts, err = z.InnerMessageType.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessageType")
		return
	}
	z.InnerMessage, bts, err = msgp.ReadBytesBytes(bts, z.InnerMessage)
	if err != nil {
		err = msgp.WrapError(err, "InnerMessage")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GeneralMessageOg) Msgsize() (s int) {
	s = 1 + z.InnerMessageType.Msgsize() + msgp.BytesPrefixSize + len(z.InnerMessage)
	return
}
