apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ogboot
spec:
  selector:
    matchLabels:
      app: ogboot
  replicas: 1
  template:
    metadata:
      labels:
        app: ogboot
    spec:
      containers:
        - name: ogboot
          image: 172.28.152.101:5000/ogboot:latest
          ports:
            - name: http
              containerPort: 8008
  -----
apiVersion: v1
kind: Service
metadata:
  name: ogboot
spec:
  type: NodePort
  ports:
    - port: 8008
      targetPort: 8008
      nodePort: 31051
      name: http
  selector:
    app: ogboot