package campaign

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *MessageCampaign) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign")
			return
		}
		z.RawCampaign = nil
	} else {
		if z.RawCampaign == nil {
			z.RawCampaign = new(RawCampaign)
		}
		var zb0002 uint32
		zb0002, err = dc.ReadArrayHeader()
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign")
			return
		}
		if zb0002 != 3 {
			err = msgp.ArrayError{Wanted: 3, Got: zb0002}
			return
		}
		err = z.RawCampaign.TxBase.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "TxBase")
			return
		}
		z.RawCampaign.DkgPublicKey, err = dc.ReadBytes(z.RawCampaign.DkgPublicKey)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "DkgPublicKey")
			return
		}
		err = z.RawCampaign.Vrf.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "Vrf")
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageCampaign) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	if z.RawCampaign == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// array header, size 3
		err = en.Append(0x93)
		if err != nil {
			return
		}
		err = z.RawCampaign.TxBase.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "TxBase")
			return
		}
		err = en.WriteBytes(z.RawCampaign.DkgPublicKey)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "DkgPublicKey")
			return
		}
		err = z.RawCampaign.Vrf.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "Vrf")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageCampaign) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	if z.RawCampaign == nil {
		o = msgp.AppendNil(o)
	} else {
		// array header, size 3
		o = append(o, 0x93)
		o, err = z.RawCampaign.TxBase.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "TxBase")
			return
		}
		o = msgp.AppendBytes(o, z.RawCampaign.DkgPublicKey)
		o, err = z.RawCampaign.Vrf.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "Vrf")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageCampaign) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.RawCampaign = nil
	} else {
		if z.RawCampaign == nil {
			z.RawCampaign = new(RawCampaign)
		}
		var zb0002 uint32
		zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign")
			return
		}
		if zb0002 != 3 {
			err = msgp.ArrayError{Wanted: 3, Got: zb0002}
			return
		}
		bts, err = z.RawCampaign.TxBase.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "TxBase")
			return
		}
		z.RawCampaign.DkgPublicKey, bts, err = msgp.ReadBytesBytes(bts, z.RawCampaign.DkgPublicKey)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "DkgPublicKey")
			return
		}
		bts, err = z.RawCampaign.Vrf.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "RawCampaign", "Vrf")
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageCampaign) Msgsize() (s int) {
	s = 1
	if z.RawCampaign == nil {
		s += msgp.NilSize
	} else {
		s += 1 + z.RawCampaign.TxBase.Msgsize() + msgp.BytesPrefixSize + len(z.RawCampaign.DkgPublicKey) + z.RawCampaign.Vrf.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageTermChange) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "RawTermChange")
			return
		}
		z.RawTermChange = nil
	} else {
		if z.RawTermChange == nil {
			z.RawTermChange = new(RawTermChange)
		}
		err = z.RawTermChange.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "RawTermChange")
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageTermChange) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	if z.RawTermChange == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.RawTermChange.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "RawTermChange")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageTermChange) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	if z.RawTermChange == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.RawTermChange.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "RawTermChange")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageTermChange) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.RawTermChange = nil
	} else {
		if z.RawTermChange == nil {
			z.RawTermChange = new(RawTermChange)
		}
		bts, err = z.RawTermChange.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "RawTermChange")
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageTermChange) Msgsize() (s int) {
	s = 1
	if z.RawTermChange == nil {
		s += msgp.NilSize
	} else {
		s += z.RawTermChange.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageTermChangeRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	z.Id, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MessageTermChangeRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 1
	err = en.Append(0x91)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MessageTermChangeRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 1
	o = append(o, 0x91)
	o = msgp.AppendUint32(o, z.Id)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageTermChangeRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 1 {
		err = msgp.ArrayError{Wanted: 1, Got: zb0001}
		return
	}
	z.Id, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MessageTermChangeRequest) Msgsize() (s int) {
	s = 1 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageTermChangeResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "TermChange")
			return
		}
		z.TermChange = nil
	} else {
		if z.TermChange == nil {
			z.TermChange = new(TermChange)
		}
		err = z.TermChange.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "TermChange")
			return
		}
	}
	z.Id, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MessageTermChangeResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	if z.TermChange == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.TermChange.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "TermChange")
			return
		}
	}
	err = en.WriteUint32(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageTermChangeResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	if z.TermChange == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.TermChange.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "TermChange")
			return
		}
	}
	o = msgp.AppendUint32(o, z.Id)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageTermChangeResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.TermChange = nil
	} else {
		if z.TermChange == nil {
			z.TermChange = new(TermChange)
		}
		bts, err = z.TermChange.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "TermChange")
			return
		}
	}
	z.Id, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageTermChangeResponse) Msgsize() (s int) {
	s = 1
	if z.TermChange == nil {
		s += msgp.NilSize
	} else {
		s += z.TermChange.Msgsize()
	}
	s += msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawCampaign) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	err = z.TxBase.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	z.DkgPublicKey, err = dc.ReadBytes(z.DkgPublicKey)
	if err != nil {
		err = msgp.WrapError(err, "DkgPublicKey")
		return
	}
	err = z.Vrf.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Vrf")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RawCampaign) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = z.TxBase.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	err = en.WriteBytes(z.DkgPublicKey)
	if err != nil {
		err = msgp.WrapError(err, "DkgPublicKey")
		return
	}
	err = z.Vrf.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Vrf")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RawCampaign) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o, err = z.TxBase.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	o = msgp.AppendBytes(o, z.DkgPublicKey)
	o, err = z.Vrf.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Vrf")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawCampaign) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	bts, err = z.TxBase.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	z.DkgPublicKey, bts, err = msgp.ReadBytesBytes(bts, z.DkgPublicKey)
	if err != nil {
		err = msgp.WrapError(err, "DkgPublicKey")
		return
	}
	bts, err = z.Vrf.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Vrf")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RawCampaign) Msgsize() (s int) {
	s = 1 + z.TxBase.Msgsize() + msgp.BytesPrefixSize + len(z.DkgPublicKey) + z.Vrf.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawCampaigns) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(RawCampaigns, zb0002)
	}
	for zb0001 := range *z {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			(*z)[zb0001] = nil
		} else {
			if (*z)[zb0001] == nil {
				(*z)[zb0001] = new(RawCampaign)
			}
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			if zb0003 != 3 {
				err = msgp.ArrayError{Wanted: 3, Got: zb0003}
				return
			}
			err = (*z)[zb0001].TxBase.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, zb0001, "TxBase")
				return
			}
			(*z)[zb0001].DkgPublicKey, err = dc.ReadBytes((*z)[zb0001].DkgPublicKey)
			if err != nil {
				err = msgp.WrapError(err, zb0001, "DkgPublicKey")
				return
			}
			err = (*z)[zb0001].Vrf.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, zb0001, "Vrf")
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z RawCampaigns) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004 := range z {
		if z[zb0004] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			// array header, size 3
			err = en.Append(0x93)
			if err != nil {
				return
			}
			err = z[zb0004].TxBase.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, zb0004, "TxBase")
				return
			}
			err = en.WriteBytes(z[zb0004].DkgPublicKey)
			if err != nil {
				err = msgp.WrapError(err, zb0004, "DkgPublicKey")
				return
			}
			err = z[zb0004].Vrf.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, zb0004, "Vrf")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z RawCampaigns) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0004 := range z {
		if z[zb0004] == nil {
			o = msgp.AppendNil(o)
		} else {
			// array header, size 3
			o = append(o, 0x93)
			o, err = z[zb0004].TxBase.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, zb0004, "TxBase")
				return
			}
			o = msgp.AppendBytes(o, z[zb0004].DkgPublicKey)
			o, err = z[zb0004].Vrf.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, zb0004, "Vrf")
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawCampaigns) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(RawCampaigns, zb0002)
	}
	for zb0001 := range *z {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			(*z)[zb0001] = nil
		} else {
			if (*z)[zb0001] == nil {
				(*z)[zb0001] = new(RawCampaign)
			}
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			if zb0003 != 3 {
				err = msgp.ArrayError{Wanted: 3, Got: zb0003}
				return
			}
			bts, err = (*z)[zb0001].TxBase.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001, "TxBase")
				return
			}
			(*z)[zb0001].DkgPublicKey, bts, err = msgp.ReadBytesBytes(bts, (*z)[zb0001].DkgPublicKey)
			if err != nil {
				err = msgp.WrapError(err, zb0001, "DkgPublicKey")
				return
			}
			bts, err = (*z)[zb0001].Vrf.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001, "Vrf")
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z RawCampaigns) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0004 := range z {
		if z[zb0004] == nil {
			s += msgp.NilSize
		} else {
			s += 1 + z[zb0004].TxBase.Msgsize() + msgp.BytesPrefixSize + len(z[zb0004].DkgPublicKey) + z[zb0004].Vrf.Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawTermChange) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	err = z.TxBase.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	z.TermId, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "TermId")
		return
	}
	z.PkBls, err = dc.ReadBytes(z.PkBls)
	if err != nil {
		err = msgp.WrapError(err, "PkBls")
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "SigSet")
		return
	}
	if cap(z.SigSet) >= int(zb0002) {
		z.SigSet = (z.SigSet)[:zb0002]
	} else {
		z.SigSet = make([]*SigSet, zb0002)
	}
	for za0001 := range z.SigSet {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, "SigSet", za0001)
				return
			}
			z.SigSet[za0001] = nil
		} else {
			if z.SigSet[za0001] == nil {
				z.SigSet[za0001] = new(SigSet)
			}
			err = z.SigSet[za0001].DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "SigSet", za0001)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RawTermChange) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 4
	err = en.Append(0x94)
	if err != nil {
		return
	}
	err = z.TxBase.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	err = en.WriteUint64(z.TermId)
	if err != nil {
		err = msgp.WrapError(err, "TermId")
		return
	}
	err = en.WriteBytes(z.PkBls)
	if err != nil {
		err = msgp.WrapError(err, "PkBls")
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.SigSet)))
	if err != nil {
		err = msgp.WrapError(err, "SigSet")
		return
	}
	for za0001 := range z.SigSet {
		if z.SigSet[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.SigSet[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "SigSet", za0001)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RawTermChange) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 4
	o = append(o, 0x94)
	o, err = z.TxBase.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	o = msgp.AppendUint64(o, z.TermId)
	o = msgp.AppendBytes(o, z.PkBls)
	o = msgp.AppendArrayHeader(o, uint32(len(z.SigSet)))
	for za0001 := range z.SigSet {
		if z.SigSet[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.SigSet[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "SigSet", za0001)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawTermChange) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	bts, err = z.TxBase.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "TxBase")
		return
	}
	z.TermId, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "TermId")
		return
	}
	z.PkBls, bts, err = msgp.ReadBytesBytes(bts, z.PkBls)
	if err != nil {
		err = msgp.WrapError(err, "PkBls")
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "SigSet")
		return
	}
	if cap(z.SigSet) >= int(zb0002) {
		z.SigSet = (z.SigSet)[:zb0002]
	} else {
		z.SigSet = make([]*SigSet, zb0002)
	}
	for za0001 := range z.SigSet {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.SigSet[za0001] = nil
		} else {
			if z.SigSet[za0001] == nil {
				z.SigSet[za0001] = new(SigSet)
			}
			bts, err = z.SigSet[za0001].UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "SigSet", za0001)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RawTermChange) Msgsize() (s int) {
	s = 1 + z.TxBase.Msgsize() + msgp.Uint64Size + msgp.BytesPrefixSize + len(z.PkBls) + msgp.ArrayHeaderSize
	for za0001 := range z.SigSet {
		if z.SigSet[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.SigSet[za0001].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawTermChanges) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(RawTermChanges, zb0002)
	}
	for zb0001 := range *z {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			(*z)[zb0001] = nil
		} else {
			if (*z)[zb0001] == nil {
				(*z)[zb0001] = new(RawTermChange)
			}
			err = (*z)[zb0001].DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z RawTermChanges) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		if z[zb0003] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z[zb0003].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, zb0003)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z RawTermChanges) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		if z[zb0003] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z[zb0003].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, zb0003)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawTermChanges) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(RawTermChanges, zb0002)
	}
	for zb0001 := range *z {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			(*z)[zb0001] = nil
		} else {
			if (*z)[zb0001] == nil {
				(*z)[zb0001] = new(RawTermChange)
			}
			bts, err = (*z)[zb0001].UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z RawTermChanges) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		if z[zb0003] == nil {
			s += msgp.NilSize
		} else {
			s += z[zb0003].Msgsize()
		}
	}
	return
}
