package archive

//
//// Code generated by github.com/tinylib/msgp DO NOT EDIT.
//
//import (
//	"bytes"
//	"testing"
//
//	"github.com/tinylib/msgp/msgp"
//)
//
//func TestMarshalUnmarshalRawActionTx(t *testing.T) {
//	v := RawActionTx{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgRawActionTx(b *testing.B) {
//	v := RawActionTx{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgRawActionTx(b *testing.B) {
//	v := RawActionTx{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalRawActionTx(b *testing.B) {
//	v := RawActionTx{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeRawActionTx(t *testing.T) {
//	v := RawActionTx{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeRawActionTx Msgsize() is inaccurate")
//	}
//
//	vn := RawActionTx{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeRawActionTx(b *testing.B) {
//	v := RawActionTx{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeRawActionTx(b *testing.B) {
//	v := RawActionTx{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestMarshalUnmarshalRawActionTxs(t *testing.T) {
//	v := RawActionTxs{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgRawActionTxs(b *testing.B) {
//	v := RawActionTxs{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgRawActionTxs(b *testing.B) {
//	v := RawActionTxs{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalRawActionTxs(b *testing.B) {
//	v := RawActionTxs{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeRawActionTxs(t *testing.T) {
//	v := RawActionTxs{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeRawActionTxs Msgsize() is inaccurate")
//	}
//
//	vn := RawActionTxs{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeRawActionTxs(b *testing.B) {
//	v := RawActionTxs{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeRawActionTxs(b *testing.B) {
//	v := RawActionTxs{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestMarshalUnmarshalRawSequencer(t *testing.T) {
//	v := RawSequencer{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgRawSequencer(b *testing.B) {
//	v := RawSequencer{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgRawSequencer(b *testing.B) {
//	v := RawSequencer{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalRawSequencer(b *testing.B) {
//	v := RawSequencer{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeRawSequencer(t *testing.T) {
//	v := RawSequencer{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeRawSequencer Msgsize() is inaccurate")
//	}
//
//	vn := RawSequencer{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeRawSequencer(b *testing.B) {
//	v := RawSequencer{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeRawSequencer(b *testing.B) {
//	v := RawSequencer{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestMarshalUnmarshalRawSequencers(t *testing.T) {
//	v := RawSequencers{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgRawSequencers(b *testing.B) {
//	v := RawSequencers{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgRawSequencers(b *testing.B) {
//	v := RawSequencers{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalRawSequencers(b *testing.B) {
//	v := RawSequencers{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeRawSequencers(t *testing.T) {
//	v := RawSequencers{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeRawSequencers Msgsize() is inaccurate")
//	}
//
//	vn := RawSequencers{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeRawSequencers(b *testing.B) {
//	v := RawSequencers{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeRawSequencers(b *testing.B) {
//	v := RawSequencers{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestMarshalUnmarshalRawTx(t *testing.T) {
//	v := RawTx{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgRawTx(b *testing.B) {
//	v := RawTx{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgRawTx(b *testing.B) {
//	v := RawTx{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalRawTx(b *testing.B) {
//	v := RawTx{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeRawTx(t *testing.T) {
//	v := RawTx{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeRawTx Msgsize() is inaccurate")
//	}
//
//	vn := RawTx{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeRawTx(b *testing.B) {
//	v := RawTx{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeRawTx(b *testing.B) {
//	v := RawTx{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestMarshalUnmarshalRawTxs(t *testing.T) {
//	v := RawTxs{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgRawTxs(b *testing.B) {
//	v := RawTxs{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgRawTxs(b *testing.B) {
//	v := RawTxs{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalRawTxs(b *testing.B) {
//	v := RawTxs{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeRawTxs(t *testing.T) {
//	v := RawTxs{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeRawTxs Msgsize() is inaccurate")
//	}
//
//	vn := RawTxs{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeRawTxs(b *testing.B) {
//	v := RawTxs{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeRawTxs(b *testing.B) {
//	v := RawTxs{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestMarshalUnmarshalTxisMarshaler(t *testing.T) {
//	v := TxisMarshaler{}
//	bts, err := v.MarshalMsg(nil)
//	if err != nil {
//		t.Fatal(err)
//	}
//	left, err := v.UnmarshalMsg(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
//	}
//
//	left, err = msgp.Skip(bts)
//	if err != nil {
//		t.Fatal(err)
//	}
//	if len(left) > 0 {
//		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
//	}
//}
//
//func BenchmarkMarshalMsgTxisMarshaler(b *testing.B) {
//	v := TxisMarshaler{}
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.MarshalMsg(nil)
//	}
//}
//
//func BenchmarkAppendMsgTxisMarshaler(b *testing.B) {
//	v := TxisMarshaler{}
//	bts := make([]byte, 0, v.Msgsize())
//	bts, _ = v.MarshalMsg(bts[0:0])
//	b.SetBytes(int64(len(bts)))
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		bts, _ = v.MarshalMsg(bts[0:0])
//	}
//}
//
//func BenchmarkUnmarshalTxisMarshaler(b *testing.B) {
//	v := TxisMarshaler{}
//	bts, _ := v.MarshalMsg(nil)
//	b.ReportAllocs()
//	b.SetBytes(int64(len(bts)))
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		_, err := v.UnmarshalMsg(bts)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
//
//func TestEncodeDecodeTxisMarshaler(t *testing.T) {
//	v := TxisMarshaler{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//
//	m := v.Msgsize()
//	if buf.Len() > m {
//		t.Log("WARNING: TestEncodeDecodeTxisMarshaler Msgsize() is inaccurate")
//	}
//
//	vn := TxisMarshaler{}
//	err := msgp.Decode(&buf, &vn)
//	if err != nil {
//		t.Error(err)
//	}
//
//	buf.Reset()
//	msgp.Encode(&buf, &v)
//	err = msgp.NewReader(&buf).Skip()
//	if err != nil {
//		t.Error(err)
//	}
//}
//
//func BenchmarkEncodeTxisMarshaler(b *testing.B) {
//	v := TxisMarshaler{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	en := msgp.NewWriter(msgp.Nowhere)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		v.EncodeMsg(en)
//	}
//	en.Flush()
//}
//
//func BenchmarkDecodeTxisMarshaler(b *testing.B) {
//	v := TxisMarshaler{}
//	var buf bytes.Buffer
//	msgp.Encode(&buf, &v)
//	b.SetBytes(int64(buf.Len()))
//	rd := msgp.NewEndlessReader(buf.KeyBytes(), b)
//	dc := msgp.NewReader(rd)
//	b.ReportAllocs()
//	b.ResetTimer()
//	for i := 0; i < b.N; i++ {
//		err := v.DecodeMsg(dc)
//		if err != nil {
//			b.Fatal(err)
//		}
//	}
//}
